version: '3.7'
services:
  keycloak-authorization-server:
    image: quay.io/keycloak/keycloak:legacy
    hostname: keycloak-server
    ports:
      - "9091:9091"
    environment:
      - "KEYCLOAK_USER=admin"
      - "KEYCLOAK_PASSWORD=admin"
      - "JAVA_OPTS=-Djboss.http.port=9091"
      - "DB_VENDOR=POSTGRES"
      - "DB_ADDR=host.docker.internal"
      - "DB_DATABASE=keycloak"
      - "DB_USER=keycloak"
      - "DB_SCHEMA=keycloak"
      - "DB_PASSWORD=keycloak"
    networks:
      - ${GLOBAL_NETWORK:-keyloack}
    depends_on:
      - keycloak-database

  keycloak-database:
      image: postgres:13.2-alpine
      environment:
        POSTGRES_USER: “keycloak”
        POSTGRES_DB: “keycloak”
        POSTGRES_PASSWORD: "keycloak"
      volumes:
        - keycloak_data:/var/lib/postgresql/data
      networks:
        - ${GLOBAL_NETWORK:-database}

volumes:
  keycloak_data: