spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/miguel-r-matos-alb/spring-cloud-config-server-repository.git
          default-label: main
          username: miguel-r-matos-alb
          password: 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
          clone-on-start: true
    fail-fast: true
  security:
    user:
      name: spring_cloud_user
      password: springCloud_Pwd!

server:
  port: 8888

logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG

log:
  app-name: config-server